### ISSUE TITLE
Compiled Error's

### ISSUE THREAD

**Issue by uhhdexz** [xo1337/cpp-rust-internal#1]
I need: 
#include "includes.hpp"  
#include "modules.hpp" 

Im using this project to learn, I'd really appreciate it :3

**Comment by xo1337** [comment]
Yes, Sorry about that. I haven't uploaded the rest of the files by accident. They're now uploaded so you should be able to compile it. Although I didn't include the il2cpp.h file because its too big in size to upload on github. So you'll need to get it yourself from using IL2CPP dumper to dump the game.

**Comment by uhhdexz** [comment]
Again Thank Alot, hopefully i'll learn more about rust int with this src
